### ISSUE TITLE
Accuracy problem

### ISSUE THREAD

**Issue by gybwyy-art** [zjy2050/HDCRL-ReID#3]
Hello, I used 4 2080ti GPUs to reproduce the code on market1501. The mAP value only reached 79.6%. Is this normal? In addition, I found that model_ ema mAP value remains unchanged at 1.5%. Is this normal?

**Comment by zjy2050** [comment]
Sorry that in hdcrl.trainers.py line 158 the '#' should be removed, and it has been corrected.
You said that the baseline mAP is 79.6%, it is normal. And the mAP value of model_ema will reach the reported results.
Any other questions welcome to add my Weixin zhou242120
